import { render } from 'preact'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen' // Generated by the plugin

const router = createRouter({ routeTree })

// Register for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

render(<RouterProvider router={router} />, document.getElementById('app')!)

